language: python
python:
- 3.6
- 3.5
- 3.4
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: aoyono
  password:
    secure: Cf3AQwHIRC1MbzWhAEqfbdo6sxXG1KbS+2k+sUZjzfKs+NdSOC3uTF05sYjd+3RMj8qnSiIqu3w2Z8wAs9DFgBwEQstBjqk54pFrHVQRkUoG7BS9lKE0bnyPMQHKrdo/n4c5uQDk26m4tYF3RvBNs2q1FdRtNtGLdXwSz27NiAQ7q14t6YHX5OTEPYrB09y/+JlaUj5va9VTOw2yyxQ/A+DakIJxiKE6gOLtOCijMiTZhiAM8XSdx2p3lALgGK+dl8Ps4jEnBR7pqfop1/PcbnyZ+T43tufPtuTn9dcwXgU29LzNrNfcbjKKQad4cgxWNtHPrx7AR77qQUHoHejV/zvLmX1XSg+NY5XvzNghl3eHpOAc3SQIsK5CWO5WE7z95vM3R2tQ2tMvAS+7Bq/YM8WhhfAJBhHqCPITxVBaU3B+/F3PONQLcOkLe4Q3YVsYbe4OaVSZdDAOECjMJBcor+szG7iQ9WOVAVjBJNsWUkx77MP9z7retn4taya3PuRUDMAPuSmVcgxf53j2x2PeZujB41dKOBS4JxLt4ardHzk2adn+Lr3saSRF5ee+eE+9mZguecTkfB1dVY+ramdV1cKiM1kaXK39lezxBuzv1xUOQ1JQzuv9NySVeUXMwDhfGTEvXnJlBe4Fce2KAqbg6ithtFoXu8OowBKD/MhUIKg=
  on:
    tags: true
    repo: aoyono/httphs
    python: 3.6
